// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnybnmtudvafyyocpsnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpueWJubXR1ZHZhZnl5b2Nwc251Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NDQ4MDUsImV4cCI6MjA2MDMyMDgwNX0.7vi3Ib5Gm2pt8yh0Jg8vYviBzBUFrYB-ntuBCJbQmPI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);